### ISSUE TITLE
Question: Testing server of GuardiansOfAdelia

### ISSUE THREAD

**Issue by riflowth** [Lix3nn53/GuardiansOfAdelia#5]
`Do you have a testing server?` 
I would like to know how this plugin works without clone this repo and then build it by myself.
Someone might be interested in this plugin, but not in development.

Thanks for developing a really interesting open-source Minecraft MMORPG plugin. 👍

**Comment by Lix3nn53** [comment]
Hi, I am developing this for my personal mmorpg server, so yes there is a test server.

Lots of things are configurable but its nowhere close to being fully configurable. 
I am still trying to complete my project so I don't plan to work on making this friendly to everyone yet. 
Maybe after I am done with development.

But if you are interested in development to make it more friendly you can contact me on discord:
lix3nn#3975

**Comment by riflowth** [comment]
Keep up the great work ☕ , I'm interested in **Spigot Plugin Development** your repository helps me to learn this thing.
if your server finishes the development please let me know.
However, my questions have answered. so this issue ticket (question) can be closed. Thanks.
